new overall video

diff --git a/bin/screencast_encode b/bin/screencast_encode
--- a/bin/screencast_encode
+++ b/bin/screencast_encode
@@ -1,7 +1,23 @@
 #!/bin/sh
 
+ASPECT='16:9'
+WIDTH=1920
+HEIGHT=1080
+
+echo 'BEFORE'
+echo getopts ":a:w:h:"
+while getopts ":a:w:h:i:" option; do
+    case "$option" in
+    a) ASPECT=$OPTARG;;
+    w) WIDTH=$OPTARG;;
+    h) HEIGHT=$OPTARG;;
+    i) FILE=$OPTARG;;
+    \?) echo "Invalid option: -$OPTARG" >&2;;
+    esac
+done
+
 # Produce the webm
-ffmpeg -i lib/screencasts/exports/$1.mov -threads 16  -keyint_min 0 -g 250 -skip_threshold 0 -qmin 1 -qmax 51 -vcodec libvpx -b:v 1024000 -s 1920x1080 -aspect 16:9 -y lib/screencasts/exports/$1.webm
+ffmpeg -an -i lib/screencasts/exports/$FILE.mov -threads 16  -keyint_min 0 -g 250 -skip_threshold 0 -qmin 1 -qmax 51 -vcodec libvpx -b:v 1024000 -s $WIDTH\x$HEIGHT -aspect $ASPECT -y -strict -2 lib/screencasts/exports/$FILE.webm
 
 # Produce the mp4
-HandBrakeCLI --optimize --preset 'High Profile' --height 1080 --two-pass --input lib/screencasts/exports/$1.mov --output lib/screencasts/exports/$1.mp4 --encoder-preset placebo --cfr
+HandBrakeCLI -a none --optimize --preset 'High Profile' --height $HEIGHT --two-pass --input lib/screencasts/exports/$FILE.mov --output lib/screencasts/exports/$FILE.mp4 --encoder-preset placebo --cfr
